routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/users-json', 'ProposalController@getStudentsJson');

Route::group(['middleware' => ['role:Super Admin'], 'prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'SuperAdmin'], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/users', 'UserController@index')->name('user.index');
    Route::post('/users', 'UserController@store')->name('user.store');
    Route::get('/users/create', 'UserController@create')->name('user.create');
    Route::get('/users/{user}', 'UserController@edit')->name('user.edit');
    Route::put('/users/{user}', 'UserController@update')->name('user.update');
    Route::put('/users/{user}/status', 'UserController@updateStatus')->name('user.update.status');
    Route::delete('/users/{user}/destroy', 'UserController@destroy')->name('user.destroy');

    Route::get('/departments', 'DepartmentController@index')->name('department.index');
    Route::post('/departments', 'DepartmentController@store')->name('department.store');
    Route::get('/departments/create', 'DepartmentController@create')->name('department.create');
    Route::get('/departments/{department}', 'DepartmentController@edit')->name('department.edit');
    Route::put('/departments/{department}', 'DepartmentController@update')->name('department.update');
    Route::delete('/departments/{department}/destroy', 'DepartmentController@destroy')->name('department.destroy');

    Route::get('/organizations', 'OrganizationController@index')->name('organization.index');
    Route::post('/organizations', 'OrganizationController@store')->name('organization.store');
    Route::get('/organizations/create', 'OrganizationController@create')->name('organization.create');
    Route::get('/organizations/{organization}', 'OrganizationController@edit')->name('organization.edit');
    Route::put('/organizations/{organization}', 'OrganizationController@update')->name('organization.update');
    Route::delete('/organizations/{organization}/destroy', 'OrganizationController@destroy')->name('organization.destroy');

    Route::get('/events', 'EventController@index')->name('events.index');
    Route::post('/events', 'EventController@store')->name('events.store');
    Route::get('/events/create', 'EventController@create')->name('events.create');
    Route::get('/events/{event}', 'EventController@edit')->name('events.edit');
    Route::put('/events/{event}', 'EventController@update')->name('events.update');
    Route::delete('/events/{event}/destroy', 'EventController@destroy')->name('events.destroy');
});

Route::group(['middleware' => ['role:Mahasiswa'], 'prefix' => 'mahasiswa', 'as' => 'mahasiswa.'], function () {
    Route::get('/home', 'MahasiswaController@index')->name('home');

    Route::get('/proposals', 'ProposalController@index')->name('proposal.index');
    Route::get('/proposals/create-option', 'ProposalController@getOption')->name('proposal.option');
    Route::get('/proposals/create', 'ProposalController@create')->name('proposal.create');
    Route::post('/proposals', 'ProposalController@store')->name('proposal.store');
    Route::get('/proposals/{proposal}', 'ProposalController@edit')->name('proposal.edit');
    Route::put('/proposals/{proposal}', 'ProposalController@update')->name('proposal.update');
    Route::get('/proposals/{proposal}/team', 'ProposalController@editTeam')->name('proposal.edit.team');
    Route::put('/proposals/{proposal}/team', 'ProposalController@updateTeam')->name('proposal.update.team');
    Route::put('/proposals/{proposal}/revision', 'ProposalController@confirmRevision')->name('proposal.revision');
    Route::delete('/proposals/{proposal}/destroy', 'ProposalController@destroy')->name('proposal.destroy');

    Route::get('/lpj/{proposal}/create', 'LpjController@create')->name('lpj.create');
    Route::post('/lpj', 'LpjController@store')->name('lpj.store');
    Route::get('/lpj/{proposal}/edit', 'LpjController@edit')->name('lpj.edit');
    Route::put('/lpj/{proposal}/edit', 'LpjController@update')->name('lpj.update');

    Route::get('/documentation/{proposal}/create', 'DocumentationController@create')->name('documentation.create');
    Route::post('/documentation/{proposal}', 'DocumentationController@store')->name('documentation.store');
    Route::delete('/documentation/{proposal}/destroy/{photo}', 'DocumentationController@destroy')->name('documentation.destroy');

    Route::get('/achievement/{proposal}/create', 'AchievementController@create')->name('achievement.create');
    Route::post('/achievement/{proposal}', 'AchievementController@store')->name('achievement.store');
    Route::delete('/achievement/{proposal}/destroy/{certificate}', 'AchievementController@destroy')->name('achievement.destroy');

    Route::get('/achievement-request', 'AchievementController@createRequest')->name('achievement-request');
    Route::post('/achievement-upload', 'AchievementController@storeRequest')->name('achievement-upload');

});

Route::group(['middleware' => ['role:Dekan'], 'prefix' => 'dekan', 'as' => 'dekan.'], function () {
    Route::get('/home', 'DekanController@index')->name('home');

    Route::put('/proposals/review/{proposalId}', 'DekanController@review')->name('proposal.review.store');
    Route::get('/proposals/review/{proposalId}/user-history', 'DekanController@getUserHistory')->name('user.history.index');

    Route::post('/mails/{mail}/sign', 'MailController@sign')->name('mail.sign');

    Route::put('/dispositions', 'DispositionController@reDisposition')->name('reDisposition');
});

Route::group(['middleware' => ['role:Wadek II'], 'prefix' => 'wadek2', 'as' => 'wadek2.'], function () {
    Route::get('/home', 'Wadek2Controller@index')->name('home');
});

Route::group(['middleware' => ['role:Wadek III'], 'prefix' => 'wadek3', 'as' => 'wadek3.'], function () {
    Route::get('/home', 'Wadek3Controller@index')->name('home');
});

Route::group(['middleware' => ['role:Kabag'], 'prefix' => 'kabag', 'as' => 'kabag.'], function () {
    Route::get('/home', 'KabagController@index')->name('home');
});

Route::group(['middleware' => ['role:Kasubag|Keuangan'], 'prefix' => 'kasubag', 'as' => 'kasubag.'], function () {
    Route::get('/home', 'KasubagController@index')->name('home');

    Route::get('/lpj', 'LpjController@index')->name('lpj.index');
    Route::post('/lpj/{proposal}/confirm', 'LpjController@confirm')->name('lpj.confirm');
    Route::post('/lpj/{proposal}/revision', 'LpjController@revision')->name('lpj.revision');

    Route::put('/lpj/{proposal}/confirm-complete', 'LpjController@confirmComplete')->name('lpj.confirm-complete');
});

Route::group(['middleware' => ['role:Sekretaris Dekan'], 'prefix' => 'sekdek', 'as' => 'sekdek.'], function () {
    Route::get('/home', 'SekdekController@index')->name('home');

    Route::get('/mails/request', 'MailController@getMailRequest')->name('mail.request');
    Route::get('/mails/{mail}/create', 'MailController@create')->name('mail.create');

    Route::get('/budgets', 'BudgetController@create')->name('budget.create');
    Route::post('/budgets', 'BudgetController@store')->name('budget.store');
    Route::get('/budgets/{year}', 'BudgetController@edit')->name('budget.edit');
    Route::put('/budgets/{year}', 'BudgetController@update')->name('budget.update');
});

Route::group(['middleware' => ['role:Dekan|Wadek II|Kabag|Kasubag|Keuangan']], function () {
    Route::get('/dispositions', 'DispositionController@index')->name('disposition.index');
    Route::post('/dispositions', 'DispositionController@store')->name('disposition.store');
    Route::get('/dispositions/{proposal}', 'DispositionController@show')->name('disposition.show');
});

Route::group(['middleware' => ['role:Dekan|Sekretaris Dekan']], function () {
    Route::get('/mails', 'MailController@index')->name('mail.index');
    Route::post('/mails', 'MailController@store')->name('mail.store');
    Route::put('/mails/{mail}', 'MailController@update')->name('mail.update');
    Route::get('/mails/{mail}/revision', 'MailController@showRevision')->name('mail.show.revision');
    Route::put('/mails/{mail}/revision', 'MailController@revision')->name('mail.revision');
});

//Route::group(['middleware' => ['role:Dekan|Wadek III']], function () {
//    Route::get('/user-achievements', 'AchievementController@getAchievementsHistories')->name('user-achievements');
//});

Route::group(['middleware' => ['role:Dekan|Kabag|Kasubag|Keuangan|Sekretaris Dekan|Mahasiswa']], function () {
    Route::get('/documentation/{proposal}', 'DocumentationController@index')->name('documentation.index');
    Route::get('/achievement/{proposal}', 'AchievementController@index')->name('achievement.index');
});

Route::group(['middleware' => ['role:Dekan|Wadek II|Wadek III|Kabag|Kasubag|Sekretaris Dekan']], function () {
    Route::get('/disposition-histories', 'DispositionController@getHistory')->name('disposition.history.index');
    Route::get('/mail-histories', 'MailController@getHistory')->name('mail.history.index');

    Route::get('/chart-funding-statistic', 'ChartController@getFundingStatistic')->name('chart.funding-statistic');
    Route::get('/chart-funding-proposal-type', 'ChartController@getFundingProposalType')->name('chart.funding-proposal-type');
    Route::get('/chart-achievement-department', 'ChartController@getAchievementDepartment')->name('chart.achievement-department');

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'department_id', 'name', 'email', 'phone', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [];

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = Hash::make($password);
    }

    public function department(){
        return $this->belongsTo(Model\Department::class, 'department_id', 'id');
    }

    public function proposals(){
        return $this->belongsToMany(Model\Proposal::class, 'teams', 'user_id', 'proposal_id');
    }

    public function dispositionSenders(){
        return $this->hasMany(Model\Disposition::class, 'form_id', 'id');
    }

    public function dispositionReceivers(){
        return $this->hasMany(Model\Disposition::class, 'to_id', 'id');
    }

    public function achievements(){
        return $this->hasMany(Model\Achievement::class, 'user_id', 'id');
    }
}

app/Http/Controllers/SuperAdmin/DepartmentController.php
<?php

namespace App\Http\Controllers\SuperAdmin;

use App\Http\Controllers\Controller;
use App\Http\Requests\DepartmentStoreRequest;
use App\Model\Department;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class DepartmentController extends Controller
{
    private function findDepartment($id){
        $department = Department::find($id);

        if(!$department){
            return null;
        }

        return $department;
    }

    public function index(Request $request){
        if($request->ajax()){
            Carbon::setLocale('id');

            $departments = Department::orderBy('name', 'ASC')->get();

            return DataTables::of($departments)
                ->removeColumn('updated_at')
                ->addIndexColumn()
                ->addColumn('action', function ($row){
                    return view('superadmin.department.datatables.sub-menu', compact('row'))->render();
                })
                ->editColumn('created_at', function ($row){
                    return $row->created_at->diffForHumans();
                })
                ->rawColumns(['action', 'status'])
                ->make(true);
        }

        return view('superadmin.department.index');
    }

    public function create(){
        return view('superadmin.department.create');
    }

    public function store(DepartmentStoreRequest $request){
        $department = new Department();
        $department->name = $request->name;
        $department->save();

        return redirect(route('admin.department.index'))->with('success', 'Berhasil menambahkan jurusan');
    }

    public function edit($id){
        $department = $this->findDepartment($id);

        if(!$department){
            return redirect(route('admin.department.index'))->with('error', 'Data tidak ditemukan');
        }

        return view('superadmin.department.edit', compact('department'));
    }

    public function update(Request $request, $id){
        $department = $this->findDepartment($id);

        if(!$department){
            return redirect(route('admin.department.index'))->with('error', 'Data tidak ditemukan');
        }

        $department->name = $request->name;
        $department->save();

        return redirect(route('admin.department.index'))->with('success', 'Berhasil mengubah data jurusan');
    }

    public function destroy($id){
        $department = $this->findDepartment($id);

        if(!$department){
            return redirect(route('admin.department.index'))->with('error', 'Data tidak ditemukan');
        }

        $department->delete();

        return redirect(route('admin.department.index'))->with('success', 'Berhasil menghapus data jurusan');
    }
}

app/Http/Controllers/SuperAdmin/EventController.php
<?php

namespace App\Http\Controllers\SuperAdmin;

use App\Http\Controllers\Controller;
use App\Http\Requests\EventStoreRequest;
use App\Model\Event;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class EventController extends Controller
{
    public function index(Request $request){
        if($request->ajax()){
            Carbon::setLocale('id');

            $events = Event::orderBy('name', 'ASC')->get();

            return DataTables::of($events)
                ->removeColumn('updated_at')
                ->addIndexColumn()
                ->addColumn('action', function ($row){
                    return view('superadmin.events.datatables.sub-menu', compact('row'))->render();
                })
                ->editColumn('created_at', function ($row){
                    return $row->created_at->diffForHumans();
                })
                ->rawColumns(['action', 'status'])
                ->make(true);
        }

        return view('superadmin.events.index');
    }

    public function create(){
        return view('superadmin.events.create');
    }

    public function store(EventStoreRequest $request){
        $event = new Event();
        $event->name = $request->name;
        $event->save();

        return redirect(route('admin.events.index'))->with('success', 'Berhasil menambahkan jenis kegiatan');
    }

    public function edit($id){
        $event = Event::find($id);

        if(!$event){
            return redirect(route('admin.events.index'))->with('error', 'Data tidak ditemukan');
        }

        return view('superadmin.events.edit', compact('event'));
    }

    public function update(Request $request, $id){
        $event = Event::find($id);

        if(!$event){
            return redirect(route('admin.events.index'))->with('error', 'Data tidak ditemukan');
        }

        $event->name = $request->name;
        $event->save();

        return redirect(route('admin.events.index'))->with('success', 'Berhasil mengubah data jenis kegiatan');
    }

    public function destroy($id){
        $event = Event::find($id);

        if(!$event){
            return redirect(route('admin.events.index'))->with('error', 'Data tidak ditemukan');
        }

        $event->delete();

        return redirect(route('admin.events.index'))->with('success', 'Berhasil menghapus data jenis kegiatan');
    }

}

app/Http/Controllers/SuperAdmin/HomeController.php
<?php

namespace App\Http\Controllers\SuperAdmin;

use App\Http\Controllers\Controller;
use App\Model\Department;
use App\Model\Event;
use App\Model\Organization;
use App\User;
use Illuminate\Database\Eloquent\Builder;

class HomeController extends Controller
{
    public function index(){
        $user = User::whereHas('roles', function (Builder $query){
            $query->whereNotIn('name', ['Super Admin', 'Doosen']);
        })->count();
        $organization = Organization::all()->count();
        $department = Department::all()->count();
        $event = Event::all()->count();

        return view('superadmin.home', compact('user', 'organization', 'department', 'event'));
    }
}

resources/views/superadmin/user/create.blade.php
@extends('layouts.dashboard')

@section('breadcrumb')
    {{ Breadcrumbs::render('admin.user.create') }}
@endsection

@section('content')
    <div class="card">
        {!! Form::open(['route' => 'admin.user.store', 'method' => 'post']) !!}
        <div class="card-header">
            <strong>Form tambah pengguna</strong>
        </div>
        <div class="card-body">
            @include('superadmin.user.fields')
        </div>
        <div class="card-footer">
            {{ Form::button('<i class="fa fa-check"></i> Simpan', ['class' => 'btn btn-sm btn-primary', 'type' => 'submit']) }}
            <a class="btn btn-sm btn-danger" href="{{route('admin.user.index')}}"><i class="fa fa-rotate-left"></i> Kembali</a>
        </div>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/superadmin/user/edit.blade.php
@extends('layouts.dashboard')

@section('breadcrumb')
    {{ Breadcrumbs::render('admin.user.create') }}
@endsection

@section('content')
    <div class="card">
        {!! Form::model($user, ['route' => ['admin.user.update', $user->id], 'method' => 'put']) !!}
        <div class="card-header">
            <strong>Form ubah data pengguna</strong>
        </div>
        <div class="card-body">
            @include('superadmin.user.fields-edit')
        </div>
        <div class="card-footer">
            {{ Form::button('<i class="fa fa-check"></i> Simpan', ['class' => 'btn btn-sm btn-primary', 'type' => 'submit']) }}
            <a class="btn btn-sm btn-danger" href="{{route('admin.user.index')}}"><i class="fa fa-rotate-left"></i> Kembali</a>
        </div>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/superadmin/user/fields-edit.blade.php
<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            {!! Form::label('id', 'NIM atau NIP') !!}
            {!! Form::number('id', null, ['id' => 'id', 'class' => 'form-control '.($errors->has('id') ? 'is-invalid' : ''), 'placeholder' => 'contoh: 1511xxx', 'autocomplete' => 'id']) !!}
            @error('id')
                <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            {!! Form::label('name', 'Nama lengkap') !!}
            {!! Form::text('name', null, ['id' => 'name', 'class' => 'form-control '.($errors->has('name') ? 'is-invalid' : ''), 'placeholder' => 'Nama Lengkap', 'autocomplete' => 'name']) !!}
            @error('name')
                <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>
    </div>

    <div class="col-sm-6">
        <div class="form-group">
            {!! Form::label('email', 'Email') !!}
            {!! Form::email('email', null, ['id' => 'email', 'class' => 'form-control '.($errors->has('email') ? 'is-invalid' : ''), 'placeholder' => 'contoh: mahasiswa@unand.ac.id', 'autocomplete' => 'email']) !!}
            @error('email')
                <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            {!! Form::label('department', 'Jurusan') !!}
            {!! Form::select('department', $departments, $departmentId, ['id' => 'department', 'class' => 'form-control '.($errors->has('department') ? 'is-invalid' : ''), 'placeholder' => 'pilih jurusan']) !!}
            @error('department')
                <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>
    </div>

    <div class="col-sm-6">
        <div class="form-group">
            {!! Form::label('role', 'Role') !!}
            {!! Form::select('role', $roles, $roleId, ['id' => 'role', 'class' => 'form-control '.($errors->has('role') ? 'is-invalid' : ''), 'placeholder' => 'pilih role']) !!}
            @error('role')
            <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>
    </div>
</div>

resources/views/superadmin/user/fields.blade.php
<div class="row">
    <div class="col-sm-6">
        <div class="form-group">
            {!! Form::label('id', 'NIM atau NIP') !!}
            {!! Form::number('id', null, ['id' => 'id', 'class' => 'form-control '.($errors->has('id') ? 'is-invalid' : ''), 'placeholder' => 'contoh: 1511xxx', 'autocomplete' => 'id']) !!}
            @error('id')
                <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            {!! Form::label('name', 'Nama lengkap') !!}
            {!! Form::text('name', null, ['id' => 'name', 'class' => 'form-control '.($errors->has('name') ? 'is-invalid' : ''), 'placeholder' => 'Nama Lengkap', 'autocomplete' => 'name']) !!}
            @error('name')
                <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>
    </div>

    <div class="col-sm-6">
        <div class="form-group">
            {!! Form::label('email', 'Email') !!}
            {!! Form::email('email', null, ['id' => 'email', 'class' => 'form-control '.($errors->has('email') ? 'is-invalid' : ''), 'placeholder' => 'contoh: mahasiswa@unand.ac.id', 'autocomplete' => 'email']) !!}
            @error('email')
                <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            {!! Form::label('department', 'Jurusan') !!}
            {!! Form::select('department', $departments, null, ['id' => 'department', 'class' => 'form-control '.($errors->has('department') ? 'is-invalid' : ''), 'placeholder' => 'pilih jurusan']) !!}
            @error('department')
                <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>
    </div>

    <div class="col-sm-6">
        <div class="form-group">
            {!! Form::label('role', 'Role') !!}
            {!! Form::select('role', $roles, null, ['id' => 'role', 'class' => 'form-control '.($errors->has('role') ? 'is-invalid' : ''), 'placeholder' => 'pilih role']) !!}
            @error('role')
            <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            {!! Form::label('password', 'Password') !!}
            {!! Form::password('password', ['id' => 'password', 'class' => 'form-control '.($errors->has('password') ? 'is-invalid' : ''), 'placeholder' => 'minimal 6 karakter', 'autocomplete' => 'password']) !!}
            @error('password')
            <div class="invalid-feedback">{{ $message }}</div>
            @enderror
        </div>
    </div>
</div>

resources/views/superadmin/user/index.blade.php
@extends('layouts.dashboard')

@section('breadcrumb')
    {{ Breadcrumbs::render('admin.user') }}
@endsection

@section('content')
    <div class="card">
        <div class="card-header">
            <strong>Data Pengguna</strong>
            <a class="btn btn-sm btn-primary float-right mr-1 d-print-none" href="{{route('admin.user.create')}}">tambah</a>
        </div>
        <div class="card-body table-responsive">
            <table class="table table-hover table-bordered data-table" style="border-collapse: collapse !important">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">NIM/ NIP</th>
                    <th scope="col">Jurusan</th>
                    <th scope="col">Nama</th>
                    <th scope="col">Email</th>
                    <th scope="col">status</th>
                    <th scope="col">Terdaftar pada</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('js-script')
    <script type="text/javascript">
        $(function () {

            const table = $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('admin.user.index') }}",
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                    {data: 'id', name: 'id'},
                    {data: 'department_id', name: 'department_id'},
                    {data: 'name', name: 'name'},
                    {data: 'email', name: 'email'},
                    {data: 'status', name: 'status'},
                    {data: 'created_at', name: 'created_at'},
                    {data: 'action', name: 'action', searchable: false, orderable: false},
                ]
            });

        });
    </script>
@endsection