routes/web.php
Route::get('/users-json', 'ProposalController@getStudentsJson');

Route::group(['middleware' => ['role:Super Admin'], 'prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'SuperAdmin'], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/users', 'UserController@index')->name('user.index');
    Route::post('/users', 'UserController@store')->name('user.store');
    Route::get('/users/create', 'UserController@create')->name('user.create');
    Route::get('/users/{user}', 'UserController@edit')->name('user.edit');
    Route::put('/users/{user}', 'UserController@update')->name('user.update');
    Route::put('/users/{user}/status', 'UserController@updateStatus')->name('user.update.status');
    Route::delete('/users/{user}/destroy', 'UserController@destroy')->name('user.destroy');

    Route::get('/departments', 'DepartmentController@index')->name('department.index');
    Route::post('/departments', 'DepartmentController@store')->name('department.store');
    Route::get('/departments/create', 'DepartmentController@create')->name('department.create');
    Route::get('/departments/{department}', 'DepartmentController@edit')->name('department.edit');
    Route::put('/departments/{department}', 'DepartmentController@update')->name('department.update');
    Route::delete('/departments/{department}/destroy', 'DepartmentController@destroy')->name('department.destroy');

    Route::get('/organizations', 'OrganizationController@index')->name('organization.index');
    Route::post('/organizations', 'OrganizationController@store')->name('organization.store');
    Route::get('/organizations/create', 'OrganizationController@create')->name('organization.create');
    Route::get('/organizations/{organization}', 'OrganizationController@edit')->name('organization.edit');
    Route::put('/organizations/{organization}', 'OrganizationController@update')->name('organization.update');
    Route::delete('/organizations/{organization}/destroy', 'OrganizationController@destroy')->name('organization.destroy');

    Route::get('/events', 'EventController@index')->name('events.index');
    Route::post('/events', 'EventController@store')->name('events.store');
    Route::get('/events/create', 'EventController@create')->name('events.create');
    Route::get('/events/{event}', 'EventController@edit')->name('events.edit');
    Route::put('/events/{event}', 'EventController@update')->name('events.update');
    Route::delete('/events/{event}/destroy', 'EventController@destroy')->name('events.destroy');
});

Route::group(['middleware' => ['role:Mahasiswa'], 'prefix' => 'mahasiswa', 'as' => 'mahasiswa.'], function () {
    Route::get('/home', 'MahasiswaController@index')->name('home');

    Route::get('/proposals', 'ProposalController@index')->name('proposal.index');
    Route::get('/proposals/create-option', 'ProposalController@getOption')->name('proposal.option');
    Route::get('/proposals/create', 'ProposalController@create')->name('proposal.create');
    Route::post('/proposals', 'ProposalController@store')->name('proposal.store');
    Route::get('/proposals/{proposal}', 'ProposalController@edit')->name('proposal.edit');
    Route::put('/proposals/{proposal}', 'ProposalController@update')->name('proposal.update');
    Route::get('/proposals/{proposal}/team', 'ProposalController@editTeam')->name('proposal.edit.team');
    Route::put('/proposals/{proposal}/team', 'ProposalController@updateTeam')->name('proposal.update.team');
    Route::put('/proposals/{proposal}/revision', 'ProposalController@confirmRevision')->name('proposal.revision');
    Route::delete('/proposals/{proposal}/destroy', 'ProposalController@destroy')->name('proposal.destroy');

    Route::get('/lpj/{proposal}/create', 'LpjController@create')->name('lpj.create');
    Route::post('/lpj', 'LpjController@store')->name('lpj.store');
    Route::get('/lpj/{proposal}/edit', 'LpjController@edit')->name('lpj.edit');
    Route::put('/lpj/{proposal}/edit', 'LpjController@update')->name('lpj.update');

    Route::get('/documentation/{proposal}/create', 'DocumentationController@create')->name('documentation.create');
    Route::post('/documentation/{proposal}', 'DocumentationController@store')->name('documentation.store');
    Route::delete('/documentation/{proposal}/destroy/{photo}', 'DocumentationController@destroy')->name('documentation.destroy');

    Route::get('/achievement/{proposal}/create', 'AchievementController@create')->name('achievement.create');
    Route::post('/achievement/{proposal}', 'AchievementController@store')->name('achievement.store');
    Route::delete('/achievement/{proposal}/destroy/{certificate}', 'AchievementController@destroy')->name('achievement.destroy');

    Route::get('/achievement-request', 'AchievementController@createRequest')->name('achievement-request');
    Route::post('/achievement-upload', 'AchievementController@storeRequest')->name('achievement-upload');

});

Route::group(['middleware' => ['role:Dekan'], 'prefix' => 'dekan', 'as' => 'dekan.'], function () {
    Route::get('/home', 'DekanController@index')->name('home');

    Route::put('/proposals/review/{proposalId}', 'DekanController@review')->name('proposal.review.store');
    Route::get('/proposals/review/{proposalId}/user-history', 'DekanController@getUserHistory')->name('user.history.index');

    Route::post('/mails/{mail}/sign', 'MailController@sign')->name('mail.sign');

    Route::put('/dispositions', 'DispositionController@reDisposition')->name('reDisposition');
});

Route::group(['middleware' => ['role:Wadek II'], 'prefix' => 'wadek2', 'as' => 'wadek2.'], function () {
    Route::get('/home', 'Wadek2Controller@index')->name('home');
});

Route::group(['middleware' => ['role:Wadek III'], 'prefix' => 'wadek3', 'as' => 'wadek3.'], function () {
    Route::get('/home', 'Wadek3Controller@index')->name('home');
});

Route::group(['middleware' => ['role:Kabag'], 'prefix' => 'kabag', 'as' => 'kabag.'], function () {
    Route::get('/home', 'KabagController@index')->name('home');
});

Route::group(['middleware' => ['role:Kasubag|Keuangan'], 'prefix' => 'kasubag', 'as' => 'kasubag.'], function () {
    Route::get('/home', 'KasubagController@index')->name('home');

    Route::get('/lpj', 'LpjController@index')->name('lpj.index');
    Route::post('/lpj/{proposal}/confirm', 'LpjController@confirm')->name('lpj.confirm');
    Route::post('/lpj/{proposal}/revision', 'LpjController@revision')->name('lpj.revision');

    Route::put('/lpj/{proposal}/confirm-complete', 'LpjController@confirmComplete')->name('lpj.confirm-complete');
});

Route::group(['middleware' => ['role:Sekretaris Dekan'], 'prefix' => 'sekdek', 'as' => 'sekdek.'], function () {
    Route::get('/home', 'SekdekController@index')->name('home');

    Route::get('/mails/request', 'MailController@getMailRequest')->name('mail.request');
    Route::get('/mails/{mail}/create', 'MailController@create')->name('mail.create');

    Route::get('/budgets', 'BudgetController@create')->name('budget.create');
    Route::post('/budgets', 'BudgetController@store')->name('budget.store');
    Route::get('/budgets/{year}', 'BudgetController@edit')->name('budget.edit');
    Route::put('/budgets/{year}', 'BudgetController@update')->name('budget.update');
});

Route::group(['middleware' => ['role:Dekan|Wadek II|Kabag|Kasubag|Keuangan']], function () {
    Route::get('/dispositions', 'DispositionController@index')->name('disposition.index');
    Route::post('/dispositions', 'DispositionController@store')->name('disposition.store');
    Route::get('/dispositions/{proposal}', 'DispositionController@show')->name('disposition.show');
});

Route::group(['middleware' => ['role:Dekan|Sekretaris Dekan']], function () {
    Route::get('/mails', 'MailController@index')->name('mail.index');
    Route::post('/mails', 'MailController@store')->name('mail.store');
    Route::put('/mails/{mail}', 'MailController@update')->name('mail.update');
    Route::get('/mails/{mail}/revision', 'MailController@showRevision')->name('mail.show.revision');
    Route::put('/mails/{mail}/revision', 'MailController@revision')->name('mail.revision');
});

//Route::group(['middleware' => ['role:Dekan|Wadek III']], function () {
//    Route::get('/user-achievements', 'AchievementController@getAchievementsHistories')->name('user-achievements');
//});

Route::group(['middleware' => ['role:Dekan|Kabag|Kasubag|Keuangan|Sekretaris Dekan|Mahasiswa']], function () {
    Route::get('/documentation/{proposal}', 'DocumentationController@index')->name('documentation.index');
    Route::get('/achievement/{proposal}', 'AchievementController@index')->name('achievement.index');
});

Route::group(['middleware' => ['role:Dekan|Wadek II|Wadek III|Kabag|Kasubag|Sekretaris Dekan']], function () {
    Route::get('/disposition-histories', 'DispositionController@getHistory')->name('disposition.history.index');
    Route::get('/mail-histories', 'MailController@getHistory')->name('mail.history.index');

    Route::get('/chart-funding-statistic', 'ChartController@getFundingStatistic')->name('chart.funding-statistic');
    Route::get('/chart-funding-proposal-type', 'ChartController@getFundingProposalType')->name('chart.funding-proposal-type');
    Route::get('/chart-achievement-department', 'ChartController@getAchievementDepartment')->name('chart.achievement-department');

    Route::get('/user-achievements', 'AchievementController@getAchievementsHistories')->name('user-achievements');
});

Route::group(['middleware' => ['role:Dekan|Wadek II|Wadek III|Kabag|Kasubag|Sekretaris Dekan|Mahasiswa']], function () {
    Route::get('/mails/{mail}', 'MailController@show')->name('mail.show');

    Route::get('/files/{id}/download', 'FileController@download')->name('file.download');
    Route::get('/files/{type}/download/{name}', 'FileController@downloadByName')->name('file.download-by-name');

resources/views/disposition/datatables/action.blade.php
<div class="btn-group-vertical" role="group" aria-label="Vertical button group">
    @if($row->organization_id)
        <a target="_blank" href="{!! url('storage/'.$row->committee_url) !!}" class="btn btn-info"><small>Struktur Kepanitiaan</small></a>
    @else
        <button type="button" class="btn btn-sm btn-info" data-toggle="modal" data-target="#team-{{$row->id}}">
            Pengusul
        </button>
    @endif
    <a target="_blank" href="{!! url('storage/'.$row->cover_letter_url) !!}" class="btn btn-info"><small>Surat Pengantar</small></a>
    <a target="_blank" href="{!! url('storage/'.$row->proposal_url) !!}" class="btn btn-info"><small>Proposal</small></a>

    @if($row->dispositions->count() == 0)
        <button type="button" class="btn btn-behance" data-toggle="modal" data-target="#disposition-{{$row->id}}">
            Disposisi
        </button>
        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#revision-{{$row->id}}">
            Revisi
        </button>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#declined-{{$row->id}}">
            Tolak
        </button>

            <div class="modal fade" id="disposition-{{$row->id}}">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        {!! Form::open(['route' => 'disposition.store', 'method' => 'post']) !!}
                        <div class="modal-header">
                            <h4 class="modal-title">Disposisi proposal</h4>
                            <button type="button" class="close" data-dismiss="modal">×</button>
                        </div>
                        <div class="modal-body">
                            {!! Form::hidden('proposal_id', $row->id) !!}

                            @if(!$row->organization_id)
                                <b>{!! Form::label('budget', 'Rincian permohonan anggaran kebutuhan dana') !!}</b>
                                <div class="bd-example m-0">
                                    <dl class="row small m-0">
                                        <dd class="col-sm-12">
                                            <dl class="row">
                                                @foreach($row->budgets as $budget)
                                                    <dd class="col-sm-4"><i>{!! config('value.budget.'.$budget->type) !!}</i></dd>
                                                    <dd class="col-sm-8">{!! $budget->amount_rupiah !!}</dd>
                                                @endforeach
                                            </dl>
                                        </dd>
                                    </dl>
                                </div>
                            @endif

                            <b>{!! Form::label('message', 'Besaran bantuan dana') !!}</b>
                            <div class="controls">
                                <div class="input-prepend input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Rp</span>
                                    </div>
                                    {!! Form::text('funds', $row->funds_needed, ['class' => 'form-control', 'autocomplete' => 'funds']) !!}
                                </div>
                            </div>
                            <br>
                            <b>{!! Form::label('dispositionTo', 'Disposisi kepada') !!}</b>
                            {!! Form::select('dispositionTo', config('value.disposition'), null, ['class' => 'form-control', 'autocomplete' => 'dispositionTo']) !!}
                            <br>
                            <b>{!! Form::label('message', 'Pesan') !!}</b>
                            {!! Form::select('templateMsg', config('value.dispositionMessageTemplate'), null, ['class' => 'form-control', 'autocomplete' => 'templateMsg']) !!}
                            {!! Form::textarea('message', null, ['id'=> "message-{{$row->id}}", 'class' => 'form-control mb-4', 'placeholder' => 'Isi pesan (opsional)', 'rows' => 4, 'cols' => 54, 'style' => 'resize:none']) !!}
                        </div>
                        <div class="modal-footer">
                            <a target="_blank" class="btn btn-success" href="{{route('dekan.user.history.index', $row->id)}}">Lihat riwayat pengusul</a>
                            {{ Form::button('Kirim', ['class' => 'btn btn-success', 'type' => 'submit', 'name' => 'dispositionBtn', 'value' => 'disposition']) }}
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Batal</button>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
    @else
        <button type="button" class="btn btn-behance" data-toggle="modal" data-target="#reDisposition-{{$row->id}}">
            Disposisikan kembali
        </button>

        <div class="modal fade" id="reDisposition-{{$row->id}}">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        {{--{!! Form::model($row->dispositions[0], ['route' => 'dekan.reDisposition', 'method' => 'put']) !!}--}}
                        {!! Form::open(['route' => 'dekan.reDisposition', 'method' => 'put']) !!}
                        <div class="modal-header">
                            <h4 class="modal-title">Disposisi proposal</h4>
                            <button type="button" class="close" data-dismiss="modal">×</button>
                        </div>
                        <div class="modal-body">
                            {!! Form::hidden('proposal_id', $row->id) !!}

                            <b>Catatan Wakil Dekan II</b>
                            {!! Form::textarea('note', $row->dispositions[0]->message, ['id'=> "note-{{$row->id}}", 'class' => 'form-control mb-4', 'rows' => 4, 'cols' => 54, 'style' => 'resize:none', 'disabled']) !!}

                            <b>{!! Form::label('budget', 'Rincian permohonan anggaran kebutuhan dana') !!}</b>
                            @if(!$row->organization_id)
                                <div class="bd-example m-0">
                                    <dl class="row small m-0">
                                        <dd class="col-sm-12">
                                            <dl class="row">
                                                @foreach($row->budgets as $budget)
                                                    <dd class="col-sm-4"><i>{!! config('value.budget.'.$budget->type) !!}</i></dd>
                                                    <dd class="col-sm-8">{!! $budget->amount_rupiah !!}</dd>
                                                @endforeach
                                            </dl>
                                        </dd>
                                    </dl>
                                </div>
                            @endif

                            <b>{!! Form::label('message', 'Besaran bantuan dana') !!}</b>
                            <div class="controls">
                                <div class="input-prepend input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Rp</span>
                                    </div>
                                    {!! Form::text('funds', $row->funds_receive, ['class' => 'form-control', 'autocomplete' => 'funds']) !!}
                                </div>
                            </div>
                            <br>
                            <b>{!! Form::label('dispositionTo', 'Disposisi kepada') !!}</b>
                            {!! Form::select('dispositionTo', config('value.disposition'), null, ['class' => 'form-control', 'autocomplete' => 'dispositionTo', 'disabled']) !!}
                            <br>
                            <b>{!! Form::label('message', 'Pesan') !!}</b>
                            {!! Form::select('templateMsg', config('value.dispositionMessageTemplate'), null, ['class' => 'form-control', 'autocomplete' => 'templateMsg']) !!}
                            {!! Form::textarea('message', null, ['id'=> "message-{{$row->id}}", 'class' => 'form-control mb-4', 'placeholder' => 'Isi pesan (opsional)', 'rows' => 4, 'cols' => 54, 'style' => 'resize:none']) !!}
                        </div>
                        <div class="modal-footer">
                            <a target="_blank" class="btn btn-success" href="{{route('dekan.user.history.index', $row->id)}}">Lihat riwayat pengusul</a>
                            {{ Form::button('Kirim', ['class' => 'btn btn-success', 'type' => 'submit']) }}
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Batal</button>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
    @endif
</div>

{{--modal team--}}
<div class="modal fade" id="team-{{$row->id}}">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Data pengusul</h4>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body">
                <div class="col">
                    <div class="form-group row m-0">
                        <label class="col-md-4 col-form-label"><strong>NIM</strong></label>
                        <label class="col-md-6 col-form-label"><strong>Nama</strong></label>
                    </div>
                    @foreach($row->teams as $team)
                        <div class="form-group row m-0">
                            <label class="col-md-4 col-form-label">{!! $team->user_id !!}</label>
                            <label class="col-md-6 col-form-label">{!! $team->user->name !!}</label>
                        </div>
                    @endforeach
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

{{--modal revision--}}
<div class="modal fade" id="revision-{{$row->id}}">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            {!! Form::open(['route' => 'disposition.store', 'method' => 'post']) !!}
            <div class="modal-header">
                <h4 class="modal-title">Revisi proposal</h4>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body">
                {!! Form::hidden('proposal_id', $row->id) !!}

                {!! Form::label('message', 'Catatan revisi') !!}
                {!! Form::textarea('message', null, ['id'=> "revision-{{$row->id}}", 'class' => 'form-control', 'placeholder' => 'Tuliskan catatan revisi', 'rows' => 4, 'cols' => 54, 'style' => 'resize:none']) !!}
            </div>
            <div class="modal-footer">
                {{ Form::button('Kirim', ['class' => 'btn btn-success', 'type' => 'submit', 'name' => 'dispositionBtn', 'value' => 'revision']) }}
                <button type="button" class="btn btn-danger" data-dismiss="modal">Batal</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

{{--modal revision--}}
<div class="modal fade" id="declined-{{$row->id}}">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            {!! Form::open(['route' => 'disposition.store', 'method' => 'post']) !!}
            <div class="modal-header">
                <h4 class="modal-title">Tolak proposal</h4>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>
            <div class="modal-body">
                {!! Form::hidden('proposal_id', $row->id) !!}

                {!! Form::label('message', 'Alasan ditolak') !!}
                {!! Form::textarea('message', null, ['id'=> "reason-{{$row->id}}", 'class' => 'form-control', 'placeholder' => 'Tuliskan alasan ditolak', 'rows' => 4, 'cols' => 54, 'style' => 'resize:none']) !!}

            </div>
            <div class="modal-footer">
                {{ Form::button('Kirim', ['class' => 'btn btn-success', 'type' => 'submit', 'name' => 'dispositionBtn', 'value' => 'declined']) }}
                <button type="button" class="btn btn-danger" data-dismiss="modal">Batal</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/disposition/datatables/history-action.blade.php
<div class="btn-group-vertical" role="group" aria-label="Vertical button group">
    <a target="_blank" href="{!! url('storage/'.$row->proposal->proposal_url) !!}" class="btn btn-info"><small>Proposal</small></a>
</div>

resources/views/disposition/datatables/info.blade.php
<button style="text-align: left" type="button" class="btn btn-sm btn-link" data-toggle="modal" data-target="#info-{{$row->id}}">
    <i class="fa fa-info-circle"></i> {{$row->title}}
</button>

<div class="modal fade" id="info-{{$row->id}}">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Deskripsi singkat kegiatan</h4>
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                {!! $row->desc !!}
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>